### ISSUE TITLE
implement visual changes for long response carousel

### ISSUE THREAD

**Issue by hyperneutrino** [uwcsc/class-profile-2024#20]

**Comment by c4thie** [comment]
helloo so I'm unable to assign issues to myself for some reason; and I am also being denied permission to publish my branch/push changes to the branch
<img width="617" alt="Screenshot 2024-11-04 at 11 08 59 AM" src="https://github.com/user-attachments/assets/c45d0323-abc3-432e-9ad9-8066c0b8b66d">
